### PR TITLE
fix: put all ports together

### PR DESCRIPTION
**Pull request by rca0**
This is a simple adjust in kubernetes deployment.
Ports can be a list of ports so, this is my suggestion to fix it.

### CODE REVIEW

**Comment by rca0** [comment]
> @rca0 actually looks like presubmit failed because we require signed commits. Could you push a new signed one or amend existing one please.

ok @dilyevsky sorry i was busy this week, i have adjusted my git to do signed commits now...

**Comment by dilyevsky** [comment]
So it actually just needs signed-off (`git -s`) not a full-blown signature (although it's doesn't hurt) - sorry I should've been more clear about that. Also doesn't look like you're actually uploaded your public key so it's not verified =)

**Comment by rca0** [comment]
@dilyevsky looking the log os travisci i think the issue isn't commits signed.

Now my commits are verified

image

**Comment by rca0** [comment]
hey @dilyevsky 
i followed your instructions and now my commits are signed.  (i ran git -s command)
i dont know how to resolve this issue now! 
i'm stupid, its not working....

image

**Comment by dilyevsky** [comment]
No prob, this presubmit script is slightly as it checks every commit in the branch:
```shell
$ git-validation  -run DCO,short-subject,dangling-whitespace * 4c31e76 "fix: put all ports together" ... PASS
 * dd1e254 "fix: put all ports together" ... FAIL
  - FAIL - does not have a valid DCO
 * 6baa5ef "Merge branch 'master' into fix/ports-unify" ... PASS
 * 6c3619b "fix: put all ports together" ... FAIL
  - FAIL - does not have a valid DCO
 * 716c2f1 "fix: put all ports together" ... FAIL
  - FAIL - does not have a valid DCO
 * 3ac97c5 "fix: put all ports together" ... FAIL
  - FAIL - does not have a valid DCO
```
The last one is passing but it still fails the check because there are bunch of broken commits trailing behind it. Can you squash those commits? (you'll have to force push the branch). Alternatively you can just abandon this PR and create a new one.

**Comment by stevvooe** [comment]
@rca0 I squashed this into a single commit. Should be good now!

**Comment by rca0** [comment]
> @rca0 I squashed this into a single commit. Should be good now!

Great!!! thanks @dilyevsky

**Pull request merged**
